#!/usr/bin/env bash
# Script to print information about subdomains of a domain

print_domain_subdomain () {
    local domain="$1"
    local subdomain="$2"

    # Run dig command and filter answer section, handle output with awk
    dig_output=$(dig "$subdomain.$domain" +short)
    if [[ -n "$dig_output" ]]; then
        record_type=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION:/ { getline; print $4 }')
        echo "The subdomain $subdomain is a $record_type record and points to $dig_output"
    fi
}

if [ "$#" -eq 1 ]; then
    print_domain_subdomain "$1" "www"
    print_domain_subdomain "$1" "lb-01"
    print_domain_subdomain "$1" "web-01"
    print_domain_subdomain "$1" "web-02"
elif [ "$#" -eq 2 ]; then
    print_domain_subdomain "$1" "$2"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi
