#!/usr/bin/env bash

# Stop Apache2 service
pkill apache2

# Change port from 80 to 8080 in nginx config
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default

# Restart nginx service
service nginx restart

# Check nginx process status
ps aux | grep '[n]ginx'

# Check nginx port 8080
nc -z 0 8080 ; echo $?
